name: sportly
app: node@18
options:
  git:
    url: https://github.com/soccerteam-matchapp/backend.git
    branch: dev
  env:
    - name: NODE_ENV
      value: production
  install: npm i -g pnpm && pnpm install --frozen-lockfile=false --prod=false && pnpm run build
  ports: 3000
  start: pnpm start
