name: sportly
app: node@18
options:
  git:
    url: https://github.com/soccerteam-matchapp/backend.git
    branch: dev
  env:
    - name: NODE_ENV
      value: production
  install: |
    set -e
    # pnpm 확보
    if command -v corepack >/dev/null 2>&1; then
      corepack enable
      corepack prepare pnpm@9 --activate || true
    else
      npm i -g pnpm
    fi

    pnpm install --no-frozen-lockfile
    pnpm run -r build || pnpm run build

    # 빌드 산출물 확인 (로그에 남김)
    echo "---- dist listing ----"
    find dist -maxdepth 2 -type f -print || true
  ports: 3000
  start: node dist/index.js    # ← 여기! npm/pnpm 경유 없이 직접 실행
