name: sportly
app: node@18
options:
  git:
    url: https://github.com/soccerteam-matchapp/backend.git
    branch: dev
  env:
    - name: NODE_ENV
      value: production
  install: |
    # pnpm 보장 및 활성화
    if command -v corepack >/dev/null 2>&1; then
      corepack enable
      corepack prepare pnpm@9 --activate || true
    else
      npm i -g pnpm@9
    fi
    
    # pnpm이 제대로 설치되었는지 확인
    pnpm -v || { echo "❌ pnpm 설치 실패"; exit 1; }
    
    # npm을 사용하지 않도록 명시적으로 pnpm 사용
    echo "---- pnpm으로 의존성 설치 ----"
    pnpm install --no-frozen-lockfile || { echo "⚠️ 의존성 설치 실패"; exit 1; }
    
    echo "---- Swagger 병합 시작 ----"
    echo "src/swagger/openapi.yaml 확인:"
    ls -la src/swagger/openapi.yaml || echo "⚠️ openapi.yaml 없음"
    echo "src/swagger/routes.yaml 확인:"
    ls -la src/swagger/routes.yaml || echo "⚠️ routes.yaml 없음"
    
    pnpm run merge-swagger || { echo "⚠️ Swagger 병합 실패"; exit 1; }
    
    echo "---- src/swagger.yaml 생성 확인 ----"
    if [ -f "src/swagger.yaml" ]; then
      echo "✅ src/swagger.yaml 생성됨"
      wc -l src/swagger.yaml || echo "라인 수 확인 실패"
      grep -c "^  /" src/swagger.yaml || echo "경로 수 확인 실패"
      echo "---- Notification API 확인 (src) ----"
      grep -c "/notifications" src/swagger.yaml || echo "⚠️ Notification API 없음"
    else
      echo "❌ src/swagger.yaml 생성 실패!"
      exit 1
    fi
    
    echo "---- TypeScript 컴파일 시작 ----"
    pnpm exec tsc || { echo "⚠️ TypeScript 컴파일 실패"; exit 1; }
    
    echo "---- Swagger 파일 복사 ----"
    pnpm exec cpx src/swagger.yaml dist || { echo "⚠️ Swagger 파일 복사 실패"; exit 1; }
    
    echo "---- dist listing ----"
    find dist -maxdepth 2 -type f -print || true
    
    echo "---- dist/swagger.yaml 최종 확인 ----"
    if [ -f "dist/swagger.yaml" ]; then
      echo "✅ dist/swagger.yaml 존재"
      wc -l dist/swagger.yaml || echo "라인 수 확인 실패"
      grep -c "^  /" dist/swagger.yaml || echo "경로 수 확인 실패"
      echo "---- Notification API 최종 확인 ----"
      NOTIFICATION_COUNT=$(grep -c "/notifications" dist/swagger.yaml || echo "0")
      if [ "$NOTIFICATION_COUNT" -gt "0" ]; then
        echo "✅ Notification API 발견: $NOTIFICATION_COUNT개"
        grep "/notifications" dist/swagger.yaml | head -5
      else
        echo "❌ Notification API 없음!"
        echo "src/swagger.yaml 내용 확인:"
        grep "/notifications" src/swagger.yaml | head -5 || echo "src에도 없음"
      fi
    else
      echo "❌ dist/swagger.yaml 없음!"
      echo "src/swagger.yaml 확인:"
      ls -la src/swagger.yaml || echo "src/swagger.yaml도 없음"
      exit 1
    fi
  ports: 3000
  start: node dist/index.js
