name: sportly
app: node@18
options:
  git:
    url: https://github.com/soccerteam-matchapp/backend.git
    branch: dev
  env:
    - name: NODE_ENV
      value: production
  install: |
    set -e
    # pnpm 보장
    if command -v corepack >/dev/null 2>&1; then
      corepack enable
      corepack prepare pnpm@9 --activate || true
    else
      npm i -g pnpm
    fi

    pnpm -v
    pnpm install --no-frozen-lockfile
    pnpm run build

    echo "---- dist listing ----"
    find dist -maxdepth 2 -type f -print || true
    
    echo "---- swagger.yaml 확인 ----"
    if [ -f "dist/swagger.yaml" ]; then
      echo "✅ dist/swagger.yaml 존재"
      wc -l dist/swagger.yaml || echo "라인 수 확인 실패"
      grep -c "^  /" dist/swagger.yaml || echo "경로 수 확인 실패"
    else
      echo "❌ dist/swagger.yaml 없음!"
    fi
  ports: 3000
  start: node ./dist/index.js
