name: sportly
app: node@18
options:
  git:
    url: https://github.com/soccerteam-matchapp/backend.git
    branch: dev
  env:
    - name: NODE_ENV
      value: production
  install: |
    set -euxo pipefail
    corepack enable
    corepack prepare pnpm@9 --activate || npm i -g pnpm
    pnpm -v
    pnpm install --no-frozen-lockfile
    pnpm run -r build || pnpm run build
  ports: 3000
  start: pnpm start
