name: sportly
app: node@18
options:
  git:
    url: https://github.com/soccerteam-matchapp/backend.git
    branch: dev
  env:
    - name: NODE_ENV
      value: production
  install: |
    set -e
    # pnpm 보장
    if command -v corepack >/dev/null 2>&1; then
      corepack enable
      corepack prepare pnpm@9 --activate || true
    else
      npm i -g pnpm
    fi

    pnpm -v
    pnpm install --no-frozen-lockfile
    pnpm run build

    echo "---- dist listing ----"
    find dist -maxdepth 2 -type f -print || true
  ports: 3000
  start: node ./dist/index.js
